providers = ["node"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "corepack prepare pnpm@9.1.4 --activate",
  "pnpm install --force"
]
cacheDirectories = ["/root/.local/share/pnpm/store/v3"]
